#!/bin/bash

FILE="${1}";
USER=`whoami`;

if [[ "${USER}" != "root" ]]; then
  echo -e "Error: This command must be run as sudo user.\nPlease run again using the following command: \n";
  echo -e "\t\tsudo secdel <filename|foldername>\n";
  exit;
fi

if [[ "${FILE}" == "" ]]; then
  echo -e "Error: No file or folder specified. Please run again using the following command: \n";
  echo -e "\t\tsudo secdel <filename|foldername>\n";
  exit;
fi


function delete {

cd `pwd`;
echo -e "Securely delete $(pwd)/${FILE}\n";

if [[ -d "${FILE}" ]];then
  SUBFILES=$(find "${FILE}" | wc -l);
  WARNMSG="WARNING: The will perform the forensic and irreversible removal of ${FILE} and all ${SUBFILES} sub files and folders.";
else
  WARNMSG="WARNING: This will perform the forensic and irreversible removal of file ${FILE}.";
fi

echo ""
echo "${WARNMSG}";
echo "";
echo "     ***** CHOOSE YOUR DESTROYER *****";
echo "[1] Shredder (US DoD compliant 7-pass overwrite)";
echo "[2] SUPER Shredder (Gutmann 35-pass overwrite)";
read -p "Enter option [1,2] (press any other key to cancel): " LVL

if [ -z ${FILE} ]; then
  DIR="./";
else
  DIR="${FILE}";
fi;

if [[ "${LVL}" -eq 1 ]];then
  echo "Forcing recurisve deletion of ${DIR} using 7-pass Department of Defense method..";
  sudo srm -rfv --dod ${DIR};
  echo "Done! ";
elif [[ "${LVL}" -eq 2 ]];then
  echo "Forcing recurisve deletion of ${DIR} using deleting using 35-pass Gutmann Method..";
  sudo srm -rfv --gutmann ${DIR};
  echo "Done! ";
  else
    echo 'Secure deletion canceled.';
fi

}

delete;
